### ISSUE TITLE
Faster Downloads

### ISSUE THREAD

**Issue by ba11b0y** [KuroLabs/Airshare#13]
The actual file transfer process can be speeded up using a relay server exposing multiple ports for file transfer. 
Any thoughts on this?

**Comment by mohanpierce99** [comment]
That would be magic-wormhole, the sole purpose of airshare was to be completely offline. But maybe we can open up multiple ports from one sender and the receiver to collect from multiple ports. That would certainly increase the speed

**Comment by ba11b0y** [comment]
My bad, by relay I meant a local relay. Exactly similar to what you're
talking about. Let me know if this works.
Would be glad to submit a PR.

**Comment by mohanpierce99** [comment]
Sure! Work on it, benchmark it and raise a PR. We'll work it out !. 

 **Quick pointer**

Look onto this thread, this will improve the speed of downloads in Airshare by just utilising multiple connections, downloading chunks and piece them all together once its done

https://stackoverflow.com/questions/58454330/how-to-download-a-big-file-in-several-simultaneous-chunks-and-save-them-to-the-s

I guess this has a better perfomance to complexity ratio than whatever you'r already trying to achieve with the things you mentioned above. So check the benchmarks and go forward with it

**Comment by nandahkrishna** [comment]
I'm closing this as it's been a while, do open up a PR if you're interested. Thanks!
