### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by kfcx** [KuroLabs/Airshare#24]
I tried to use Airshare to share a folder, this folder is very large, about 10G, but I found that it will compress and cache on the C drive, my C drive can not accommodate the space and cause the storage overflow error, which makes me very annoyed , And I don’t know which folder on the C drive the compressed cache is placed in, so I have trouble deleting it.

**Comment by kfcx** [comment]
Finally found the compressed cache in C:\Users\23914\AppData\Local\Temp, 11G size

**Comment by nandahkrishna** [comment]
This is not a bug in Airshare. The `tempfile.mkstemp` method is used to create a temporary file (which is the Zip archive), and its location can be customised using environment variables [1] (`TMPDIR`, `TEMP` or `TMP`). You could consider setting the appropriate environment variable if your C drive doesn't have enough space.

[1] https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp
