### ISSUE TITLE
Download does not work if filename contains comma

### ISSUE THREAD

**Issue by michie1** [KuroLabs/Airshare#8]
When I have the filename called `a,b.mkv` ("a comma b dot mkv") I noticed in the web browser the filename is not being shown and the filesize as `NaN undefined`. Also downloading the file does not work, Chrome shows the errors "ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION"

![Screenshot from 2020-05-10 22-21-07](https://user-images.githubusercontent.com/1347371/81509731-21413180-930d-11ea-8842-9552403661d8.png)
![Screenshot from 2020-05-10 22-20-56](https://user-images.githubusercontent.com/1347371/81509732-21d9c800-930d-11ea-8306-76c5cd222246.png)

**Comment by nandahkrishna** [comment]
I think we'll have to wrap the filename within double quotes. We use the `content-disposition` header to make the file downloadable snd yes, a comma would prevent it from working as intended. Thanks for spotting it!

**Comment by nandahkrishna** [comment]
Fixed.
